### ISSUE TITLE
In the Hubspot integration, clicking the button "Add mapping" inside the workflow, doesn't do anything

### ISSUE THREAD

**Issue by galaxxy22** [umbraco/Umbraco.Forms.Integrations#73]
Concerns a project with the following versions:
CMS: 8.18.7
Forms: 8.12.2
Deploy: 4.6.2

Package installed: Umbraco.Forms.Integrations.Crm.Hubspot (version 1.1.1)

To reproduce:
Go to a form, go to "Configure workflow", add or edit the type "Save Contact to Hubspot", and click the "Add mapping" button.

**Comment by acoumb** [comment]
Hi @galaxxy22 ,

And apologies for the late reply. 

I have investigated the reported issue, but could not replicate it using the configuration you have. I have made a [recording](https://youtu.be/v0x7WoxjhYs) of my test case , maybe you can spot anything I'm doing differently. 

Could you also tell me if you get any console errors?

Thank you,
Adrian

**Comment by galaxxy22** [comment]
Hi Adrian,

No there are no errors in the log. After further inspection, it seems the following div keeps the class "ng-hide" which has the display: none property:
`<div class="umb-forms-mappings ng-hide" ng-show="vm.mappings.length > 0 && vm.hubspotFields.length > 0" aria-hidden="true">`

**Comment by acoumb** [comment]
Hi,

In this case it means that the HubSpot API does not return you a response with the list of contact properties, or the authorization has failed, or the request made to `https://api.hubapi.com/crm/v3/properties/contacts` returned an empty collection. And because `vm.hubspotFields` is empty, you cannot create any mappings.
A list of fields would look like this:
![image](https://user-images.githubusercontent.com/95346674/234567530-5af80b8a-1562-44af-9016-ac95a7cdf2cb.png)

The following ZIP file contains a Postman collection with a sample request to HubSpot API using private app access tokens to get the contact properties and a sample response (token is no longer valid - I just included it for reference)
[Umbraco Forms Integrations.postman_collection.zip](https://github.com/umbraco/Umbraco.Forms.Integrations/files/11332620/Umbraco.Forms.Integrations.postman_collection.zip)

Or you can check out the logs for error messages like:
- `Cannot access HubSpot API via API key or OAuth, as neither a key has been configured nor a refresh token stored.`
- `Failed to fetch contact properties from HubSpot API for mapping.`

You can also test out the API responses for your HubSpot environment using these [docs](https://developers.hubspot.com/docs/api/crm/properties).

Thank you

**Comment by galaxxy22** [comment]
Thank you for the response. I fixed the issue now. Because the Api-key is deprecated at Hubspot, you have to use the OAuth to authorize the app. What I did was remove the Api key from the UmbracoForms.config and reathenticated the integration in de workflow config of a form.

**Comment by acoumb** [comment]
Hi,

I've added support for HubSpot `Private Access Tokens` and you can now use version [2.1.0](https://www.nuget.org/packages/Umbraco.Forms.Integrations.Crm.Hubspot/2.1.0) without OAuth.

I am closing this, thank you for your input. Feel free to reach out if you have other feedback.

Adrian
